### ISSUE TITLE
BUG : 

### ISSUE THREAD

**Issue by Ambassador-pi** [XDagger/xdagj#174]
Devnet Failed to start the program. What's the problem? The error message is as follows:

root@ns550510:/usr/local/xdagj/run# sh xdag.sh -d
xdag.sh: 3: ulimit: error setting limit (Operation not permitted)
Nov 07, 2022 1:13:23 AM org.apache.commons.beanutils.FluentPropertyBeanIntrospector introspect
INFO: Error when creating PropertyDescriptor for public final void org.apache.commons.configuration2.AbstractConfiguration.setProperty(java.lang.String,java.lang.Object)! Ignoring this property.
Create New Wallet...
EnterNewPassword:
ReEnterNewPassword:
HdWallet Initializing...
HdWallet Mnemonic:embody awesome group medal layer innocent cloth matter orbit wasp tell ski
HdWallet Mnemonic Repeat:
HdWallet Initialized Failure
Exception in thread "main" java.lang.IllegalArgumentException: HD Seed is not initialized
        at io.xdag.wallet.Wallet.requireHdWalletInitialized(Wallet.java:483)
        at io.xdag.wallet.Wallet.addAccountWithNextHdKey(Wallet.java:469)
        at io.xdag.cli.XdagCli.start(XdagCli.java:253)
        at io.xdag.cli.XdagCli.start(XdagCli.java:225)
        at io.xdag.cli.XdagCli.main(XdagCli.java:149)
        at io.xdag.cli.XdagCli.main(XdagCli.java:156)
        at io.xdag.Bootstrap.main(Bootstrap.java:32)

**Comment by Xiaoan6666** [comment]
![image](https://github.com/XDagger/xdagj/assets/94225599/7b9b5c85-b10f-4d8f-bac2-ccdd861c0cac)
