### ISSUE TITLE
BUG : Exception in thread "main" cn.hutool.core.io.resource.NoResourceException: Resource of path [xdag-testnet.config] not exist!

### ISSUE THREAD

**Issue by lonperez** [XDagger/xdagj#55]
Exception in thread "main" cn.hutool.core.io.resource.NoResourceException: Resource of path [xdag-testnet.config] not exist!

when I compile xdagj and use 
_nohup java -jar --enable-preview xdagj-0.4.0-shaded.jar > xdagj.log 2>&1 &_
run the test net or main net ,It crashes.

Exception in thread "main" cn.hutool.core.io.resource.NoResourceException: Resource of path [xdag-testnet.config] not exist!
        at cn.hutool.core.io.resource.ClassPathResource.initUrl(ClassPathResource.java:122)
        at cn.hutool.core.io.resource.ClassPathResource.<init>(ClassPathResource.java:74)
        at cn.hutool.core.io.resource.ClassPathResource.<init>(ClassPathResource.java:34)
        at cn.hutool.core.io.resource.ResourceUtil.getResourceObj(ResourceUtil.java:199)
        at cn.hutool.setting.Setting.<init>(Setting.java:128)
        at cn.hutool.setting.Setting.<init>(Setting.java:116)
        at cn.hutool.setting.Setting.<init>(Setting.java:106)
        at io.xdag.config.AbstractConfig.getSetting(AbstractConfig.java:207)
        at io.xdag.config.AbstractConfig.<init>(AbstractConfig.java:153)
        at io.xdag.config.TestnetConfig.<init>(TestnetConfig.java:32)
        at io.xdag.Launcher.buildConfig(Launcher.java:102)
        at io.xdag.cli.XdagCli.start(XdagCli.java:126)
        at io.xdag.cli.XdagCli.main(XdagCli.java:59)
        at io.xdag.cli.XdagCli.main(XdagCli.java:66)
        at io.xdag.Bootstrap.main(Bootstrap.java:36)

How can i fix this problem?
I follow this tutorial step by step:
https://github.com/XDagger/xdagj/blob/master/docs/XDAGJ_Private_Chain_Tutorial_eng.md
Can anyone help me ?

**Comment by MyronX** [comment]
Please check if there is xdag-testnet.config in your resource file directory. 
Can you provide us with the code version and system version you are running, so that we can better troubleshoot the problem

**Comment by lonperez** [comment]
yes, xdag-testnet.config   in the resource file directory. I used master branch.

**Comment by MyronX** [comment]
You can try to copy xdag-testnet.config to the compiled jar package path.
If you are using a linux or macos system, you also need to copy xdag.sh in the script folder to the same path.
Try to execute  `xdag.sh -t`  to start the program.
If there are any other errors, please contact us.

**Comment by MyronX** [comment]
> yes, xdag-testnet.config in the resource file directory. I used master branch.

You can try to copy xdag-testnet.config to the compiled jar package path.
If you are using a linux or macos system, you also need to copy xdag.sh in the script folder to the same path.
Try to execute xdag.sh -t to start the program.
If there are any other errors, please contact us.

**Comment by MyronX** [comment]
> > yes, xdag-testnet.config in the resource file directory. I used master branch.
> 
> You can try to copy xdag-testnet.config to the compiled jar package path.
> If you are using a linux or macos system, you also need to copy xdag.sh in the script folder to the same path.
> Try to execute xdag.sh -t to start the program.
> If there are any other errors, please contact us.

and you also need to add your java path to the xdag.sh file
